// loading
export const SHOW_LOADING = 'SHOW_LOADING'
export const HIDE_LOADING = 'HIDE_LOADING'

// orders
export const UPDATE_ORDERSLIST = 'UPDATE_ORDERSLIST'
export const SHOW_ORDERSLIST = 'SHOW_ORDERSLIST'
export const UPDATE_FOODSMENU = 'UPDATE_FOODSMENU'
