// loading
export const SHOW_LOADING = 'SHOW_LOADING'
export const HIDE_LOADING = 'HIDE_LOADING'

// orders
export const UPDATE_ORDERSLIST = 'UPDATE_ORDERSLIST'
export const UPDATE_LISTLOADINGSTATE = 'UPDATE_LISTLOADINGSTATE'
export const UPDATE_FOODSMENU = 'UPDATE_FOODSMENU'
export const UPDATE_MENULOADINGSTATE = 'UPDATE_MENULOADINGSTATE'
